name: Deploy to Neocities

on:
  push: # this triggers the workflow on a 'push' event.
    branches: [main] # change if you want to deploy from other branches.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main # this downloads the code from repo
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: $
          cleanup: false
          dist_dir: public # Change to the folder your site is in.
